apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: aci-connector-sa
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["nodes/status"]
  resourceNames: ["aci-connector"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: aci-connector-sa
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-connector-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-connector-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-connector-sa
subjects:
- kind: ServiceAccount
  name: aci-connector-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: aci-connector-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aci-connector-sa
subjects:
- kind: ServiceAccount
  name: aci-connector-sa
  namespace: default
